pipeline {
    agent any

    
    parameters {
        choice(
            name: 'scanMode',
            choices: ['dev', 'prod_no_security', 'prod'],
            description: 'Select the Scan mode: <dev> : Will run checks without interrupting the pipeline, useful in development. <prod_no_security> : Will skip security checks in production.     <prod> : Will run full checks and stop in case of severe vulnerabilities (HIGH, CRITICAL) '
        )
    }

    environment {
        // Azure Components
        AZURE_DEFAULT_REGION = "westeurope"
        RG_NAME="BU-MT"
        AKS_NAME = "rome"

        // Docker Images
        GitLeaksImageTag = 'zricethezav/gitleaks:latest'
    }

    stages {
        stage('Azure Login') {
            steps {
                script {
                    dir('iac/terraform'){
                        withCredentials([usernamePassword(credentialsId: "certimetergroup_creds", usernameVariable: "AZURE_USERNAME", passwordVariable: "AZURE_PASSWORD")]) {     
                            sh 'az login --username $AZURE_USERNAME --password $AZURE_PASSWORD'
                        } 
                    }
                }
            }
        }
/*
        stage('Trivy Secret Scanning'){
            steps {
                script {
                    dir('iac/terraform'){ 
                        sh 'trivy filesystem . --trace'
                        sh 'trivy filesystem --format=json .'
                    }
                }
            }
            
        }
*/
        stage('GitLeaks Secret Scanning'){
            steps{
                script{
                    try{
                        if (params.scanMode == 'prod_no_security') {
                            echo("No security mode detected, skipping the actual security check")
                            return
                        }

                        // Pull the GitLeaks image
                        sh "sudo docker image pull $GitLeaksImageTag"

                        //DEV MODE
                        if(params.scanMode == 'dev') {
                            // Run GitLeaks
                            def GitLeaksScan = sh (script: "sudo docker run --rm -v .:/path $GitLeaksImageTag detect --source=/path --no-color --verbose", returnStatus: true)
                            if (GitLeaksScan == 0) {
                                echo("GitLeaks Secret Scan successfully executed, no secrets found in your code.")
                            }
                            else{
                                unstable("WARNING!!! Secrets found in your code")
                                input "Do you want the pipeline to go ahead? There are UNENCRYPTED SECRETS in your code, be aware and choose wisely."
                            }
                        }
                        //PROD MODE
                        //there is no filter in secret scanning, it's not possible to set a severity level
                        else{
                            // Run GitLeaks 
                            def GitLeaksScan = sh (script: "sudo docker run --rm -v .:/path $GitLeaksImageTag detect --source=/path --no-color --verbose", returnStatus: true)
                            if (GitLeaksScan == 0) {
                                echo("GitLeaks Secret Scan successfully executed, no secrets found in your code.")
                            }
                            else{
                                error("WARNING!!! Secrets found in your code")
                                echo("Application stopped. There are UNENCRYPTED SECRETS in your code.")
                            }
                        }
                    }
                    catch( Exception ex ){
                        error("Secret Scanning terminated with an error : ${ex.message}")
                    }  
                }
            }
                

        }

        
        stage('Terraform Init') {
            steps {
                dir('iac/terraform'){
                    sh 'terraform init -upgrade'
                }
            }
        }


        stage('Terraform Validate') {
            steps {
                dir('iac/terraform'){
                    sh "terraform validate"
                }
            }
        }

        stage('Tfsec'){
            steps {
                if (params.scanMode == 'prod_no_security') {
                    echo("No security mode detected, skipping the actual security check")
                    return
                }
                
                dir('iac/terraform'){

                    //DEV MODE
                    if(params.scanMode == 'dev') {
                        // Run GitLeaks
                        def TfsecScan = sh (script: "tfsec", returnStatus: true)
                        if (TfsecScan == 0) {
                            echo("Tfsec Scan successfully executed, no vulnerabilities found in your code.")
                        }
                        else{
                            unstable("WARNING!!! Vulnerabilities found in your code")
                            input "Do you want the pipeline to go ahead? There are VULNERABILITIES in your HCL TERRAFORM code, be aware and choose wisely."
                        }
                    }
                    //PROD MODE
                    else{
                        // Run GitLeaks 
                        def TfsecScan = sh (script: "tfsec -m HIGH", returnStatus: true)
                        if (TfsecScan == 0) {
                            echo("Tfsec Scan successfully executed, no secrets found in your code.")
                        }
                        else{
                            error("WARNING!!! Vulnerabilities found in your code")
                            echo("Application stopped. There are VULNERABILITIES in your HCL TERRAFORM code.")
                        }
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('iac/terraform'){
                    script{
                        withCredentials([usernamePassword(credentialsId: "ClientIdClientSecret", usernameVariable: "CLIENT_ID", passwordVariable: "CLIENT_SECRET")]) {     
                            sh "terraform plan -var='appId=${CLIENT_ID}' -var='password=${CLIENT_SECRET}'"
                        } 
                    }
                }   
            }        
        }

        stage('Plan approval') {
            steps {
                input "Approve the previously generated plan?"
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('iac/terraform'){
                    script{
                        withCredentials([usernamePassword(credentialsId: "ClientIdClientSecret", usernameVariable: "CLIENT_ID", passwordVariable: "CLIENT_SECRET")]) {
                            sh "terraform apply -var='appId=${CLIENT_ID}' -var='password=${CLIENT_SECRET}' -auto-approve"
                        }
                    }
                }
            }
        }

        stage('Cluster deployed or not? (stop if not)') {
            steps {
                input "Cluster deployed or not? (stop if not)"
            }
        }
        
        stage('Configurazione kubectl') {
            steps {
                sh 'az aks get-credentials --name $AKS_NAME --resource-group $RG_NAME --overwrite-existing'
            }
        }

        stage('Verifica cluster') {
            steps {
                sh "kubectl cluster-info"
            }
        }
/*
        stage('Setup Prometheus and Graphana with Helm'){ 
            steps {
                dir('iac'){
                    sh 'kubectl apply -f ingress.yaml'
                }
            }
        }
*/
        /*
        stage('Piano distruzione Terraform') {
            steps {
                dir('iac/terraform'){
                    sh "terraform plan -destroy"
                }
            }
        }
        stage('Approvazione destroy Infrastruttura') {
            steps {
                input "Approvazione destroy infrastruttura?"
            }
        }
        stage('Destroy Infrastruttura') {
            steps {
                dir('iac/terraform'){
                    sh "terraform destroy -auto-approve"
                }
            }
        }
        */
    }
}